# Generated by Django 6.0 on 2026-07-16 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_budgetitem'),
        ('users', '0006_alter_user_account_status_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='existing_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user', 'project'), name='unique_pending_registration_per_user_project'),
        ),
    ]
