# Generated by Django 5.2.9 on 2026-07-13 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_requests', '0002_add_canceled_status_and_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-updated_at', '-date_submitted']},
        ),
        migrations.AddField(
            model_name='changerequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='proposed_changes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ChangeRequestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('admin_feedback', models.TextField(blank=True, default='')),
                ('change_type', models.CharField(choices=[('ACTIVITY', 'Activity'), ('OBJECTIVE', 'Objective'), ('PERSONNEL', 'Personnel'), ('BUDGET', 'Budget'), ('COMPENSATION', 'Compensation'), ('PROJECT', 'Project'), ('ROLE', 'Role'), ('DEPARTMENT', 'Department')], max_length=20)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('current_state', models.JSONField(blank=True, null=True)),
                ('proposed_changes', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='change_requests.changerequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_request_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('change_request', 'version_number')},
            },
        ),
    ]
