# Generated by Django 5.2.9 on 2026-07-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_log', '0002_archivedhistorylog'),
        ('projects', '0012_budgetitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='archivedhistorylog',
            new_name='history_log_project_a91b77_idx',
            old_name='history_log_project_archived_at_idx',
        ),
        migrations.RenameIndex(
            model_name='archivedhistorylog',
            new_name='history_log_user_id_eff858_idx',
            old_name='history_log_user_archived_at_idx',
        ),
        migrations.RenameIndex(
            model_name='archivedhistorylog',
            new_name='history_log_change__19f319_idx',
            old_name='history_log_change_type_archived_at_idx',
        ),
        migrations.AddField(
            model_name='historylog',
            name='module',
            field=models.CharField(blank=True, default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='historylog',
            name='object_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historylog',
            name='user_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('REVERT', 'Revert'), ('ASSIGN', 'Assign'), ('REMOVE', 'Remove'), ('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historylog',
            name='change_type',
            field=models.CharField(choices=[('ACTIVITY', 'Activity'), ('OBJECTIVE', 'Objective'), ('PERSONNEL', 'Personnel'), ('BUDGET', 'Budget'), ('COMPENSATION', 'Compensation'), ('PROJECT', 'Project'), ('ROLE', 'Role'), ('DEPARTMENT', 'Department'), ('CHANGE_REQUEST', 'Change Request'), ('USER', 'User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_log_entries', to='projects.project'),
        ),
    ]
