# Generated by Django 5.2.9 on 2026-07-13 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_log', '0003_rename_history_log_project_archived_at_idx_history_log_project_a91b77_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedhistorylog',
            name='history_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_copy', to='history_log.historylog'),
        ),
    ]
