# Generated by Django 6.0 on 2026-07-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['id']},
        ),
    ]
